---
#########
# Install from the docker official repo.
#

#########
# Install docker:
# - Add the docker repository
# - and it's key
# - install
# - add vagrant user to the docker group for great justice
- name: add docker repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    validate_certs: no

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present



- name: install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
    force: yes

- name: include vagrant user in docker group
  user:
    name: vagrant
    groups: docker

#########
# Install docker engine from github.
# TODO create a var for docker-compose version.
- name: register kernel name
  shell: uname -s
  register: kernel_name

- name: register machine hardware name
  shell: uname -m
  register: hardware_name

- name: get docker engine from github
  get_url:
    url: >
      https://github.com/docker/compose/releases/download/1.19.0/docker-compose-{{ kernel_name.stdout }}-{{ hardware_name.stdout }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
